export const COLORS = {
  bg: "#f4f7fb",
  surface: "#ffffff",
  border: "#c7d3e3",
  text: "#17212f",
  muted: "#5f6f84",
  accent: "#0f766e",
  accentDim: "#0f766e1f",
  danger: "#b42318",
};

export const TONES = {
  teal: { bg: "#e8f7f5", border: "#7ecbc1", value: "#0f5f58" },
  blue: { bg: "#eaf2ff", border: "#8fb0e8", value: "#1f4f99" },
  violet: { bg: "#f3efff", border: "#a58adf", value: "#5d3d9a" },
  amber: { bg: "#fff6e8", border: "#e5bb7f", value: "#8a5a1f" },
  rose: { bg: "#ffeef4", border: "#de9fba", value: "#9a3d63" },
  green: { bg: "#ebf8ee", border: "#8dc99a", value: "#2b6a39" },
};

export const styles = {
  app: {
    minHeight: "100vh",
    background: COLORS.bg,
    color: COLORS.text,
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    padding: "28px 24px",
  },
  header: {
    marginBottom: 20,
    borderBottom: `1px solid ${COLORS.border}`,
    paddingBottom: 14,
  },
  title: {
    margin: 0,
    fontSize: 26,
    fontWeight: 700,
  },
  subtitle: {
    marginTop: 6,
    fontSize: 13,
    color: COLORS.muted,
  },
  card: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 12,
    padding: 14,
    marginBottom: 14,
  },
  drop: (over) => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    boxSizing: "border-box",
    border: `1.5px dashed ${over ? COLORS.accent : COLORS.border}`,
    borderRadius: 10,
    padding: "24px 16px",
    textAlign: "center",
    background: over ? COLORS.accentDim : "transparent",
    cursor: "pointer",
    transition: "all .15s",
  }),
  btn: {
    marginTop: 10,
    padding: "8px 14px",
    borderRadius: 8,
    border: `1px solid ${COLORS.border}`,
    background: "transparent",
    color: COLORS.text,
    cursor: "pointer",
    fontSize: 13,
  },
  status: (type) => ({
    display: "block",
    borderRadius: 8,
    padding: "8px 10px",
    marginBottom: 12,
    fontSize: 13,
    background: type === "error" ? "#ffe9e7" : "#e8f6f4",
    color: type === "error" ? COLORS.danger : COLORS.text,
  }),
  fileInfo: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
    marginBottom: 12,
  },
  resultPanel: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "78vh",
    minHeight: 0,
  },
  stickyHeader: {
    position: "sticky",
    top: 0,
    zIndex: 5,
    background: COLORS.surface,
    borderBottom: `1px solid ${COLORS.border}`,
    paddingBottom: 10,
  },
  scrollContent: {
    overflowY: "auto",
    minHeight: 0,
    paddingTop: 10,
  },
  infoPill: (tone) => ({
    border: `1px solid ${tone.border}`,
    borderRadius: 8,
    background: tone.bg,
    padding: "8px 10px",
    minWidth: 150,
  }),
  infoLabel: {
    display: "block",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: COLORS.muted,
    marginBottom: 4,
  },
  infoValue: (tone) => ({
    display: "block",
    fontSize: 14,
    fontWeight: 700,
    color: tone.value,
    lineHeight: 1.2,
    wordBreak: "break-word",
  }),
  tabs: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 12,
    paddingBottom: 2,
  },
  tab: (active, tone) => ({
    border: `1px solid ${active ? tone.border : COLORS.border}`,
    background: active ? tone.bg : "#f5f8fc",
    color: active ? tone.value : COLORS.text,
    padding: "10px 12px",
    borderRadius: 10,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: active ? 700 : 500,
    transition: "all .15s",
    textAlign: "left",
    minHeight: 66,
  }),
  tabLabel: {
    display: "block",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: COLORS.muted,
    marginBottom: 4,
  },
  tabCount: (active, tone) => ({
    display: "block",
    fontSize: 22,
    fontWeight: 700,
    lineHeight: 1,
    color: active ? tone.value : COLORS.text,
  }),
  tableWrap: {
    overflow: "auto",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
  },
  th: {
    textAlign: "left",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: COLORS.muted,
    padding: "8px 10px",
    borderBottom: `1px solid ${COLORS.border}`,
    background: "#edf3fb",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "8px 10px",
    borderBottom: `1px solid ${COLORS.border}`,
    verticalAlign: "top",
  },
  mono: {
    fontFamily: "'DM Mono', 'Courier New', monospace",
    fontSize: 12,
  },
  codeBlock: {
    background: "#f6f9ff",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    padding: "10px 12px",
    fontFamily: "'DM Mono', 'Courier New', monospace",
    fontSize: 12,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    marginBottom: 10,
  },
  historyCard: (tone) => ({
    border: `2px solid ${tone.border}`,
    borderRadius: 12,
    background: `linear-gradient(180deg, #ffffff, #fbfdff), linear-gradient(90deg, ${tone.border}2a 0%, transparent 26%, transparent 74%, ${tone.border}2a 100%)`,
    boxShadow: `inset 0 0 0 1px ${tone.border}33`,
    padding: 12,
    marginBottom: 12,
  }),
  historyHeaderRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 10,
  },
  historyToggleButton: {
    width: "100%",
    border: "none",
    background: "transparent",
    padding: 0,
    margin: 0,
    cursor: "pointer",
    textAlign: "left",
  },
  historyTitle: {
    fontSize: 16,
    fontWeight: 900,
    color: "#111b2a",
    lineHeight: 1.2,
  },
  historySubline: {
    marginTop: 3,
    fontSize: 12,
    color: "#2a3e5f",
    fontWeight: 700,
    lineHeight: 1.4,
  },
  historyBadge: (tone) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    padding: "4px 8px",
    border: `1px solid ${tone.border}`,
    background: tone.bg,
    color: tone.value,
    fontSize: 11,
    fontWeight: 700,
  }),
  historySection: {
    marginTop: 10,
  },
  historySectionLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: COLORS.muted,
    marginBottom: 6,
    fontWeight: 700,
  },
  historyOptionsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 8,
  },
  historyOption: {
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    background: "#ffffff",
    padding: "8px 10px",
  },
  historyOptionKey: {
    fontSize: 11,
    letterSpacing: "0.05em",
    color: COLORS.muted,
    marginBottom: 3,
    fontWeight: 700,
    wordBreak: "break-word",
  },
  historyOptionValue: {
    fontSize: 12,
    color: COLORS.text,
    wordBreak: "break-word",
    lineHeight: 1.35,
  },
  historyGreyBox: {
    background: "#f2f6fc",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    padding: "10px 12px",
  },
  nullOptionsBox: {
    marginTop: 10,
    border: `1px solid ${TONES.amber.border}`,
    borderRadius: 10,
    background: "#fff7ea",
    padding: "12px 14px",
  },
  nullOptionsTitle: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: TONES.amber.value,
    fontWeight: 800,
    marginBottom: 6,
  },
  nullOptionsText: {
    fontSize: 12,
    lineHeight: 1.45,
    color: COLORS.text,
    wordBreak: "break-word",
  },
  helpIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
    width: 16,
    height: 16,
    borderRadius: 999,
    border: `1px solid ${COLORS.border}`,
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: 700,
    cursor: "help",
    userSelect: "none",
  },
};
