export const COLORS = {
  bg: "#f5f7fb",
  surface: "#ffffff",
  border: "#d8deea",
  text: "#1f2937",
  muted: "#5f6b7a",
  accent: "#0f766e",
  accentSoft: "#ccfbf1",
  soonBg: "#eef2ff",
  soonText: "#4f46e5",
  betaBg: "#fff7ed",
  betaText: "#c2410c",
  experimentalBg: "#fdf2f8",
  experimentalText: "#be185d",
  affiliateBg: "#4f46e5",
  affiliateText: "#eef2ff",
  defaultBadgeBg: "#f3f4f6",
  defaultBadgeText: "#374151",
};

export const styles = {
  page: {
    minHeight: "100vh",
    background: COLORS.bg,
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    color: COLORS.text,
  },
  topbar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 20px",
    background: COLORS.surface,
    borderBottom: `1px solid ${COLORS.border}`,
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  topbarTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: COLORS.text,
  },
  topbarSubtitle: {
    marginLeft: "auto",
    fontSize: 12,
    color: COLORS.muted,
  },
  home: {
    maxWidth: 1040,
    margin: "0 auto",
    padding: "28px 10px 36px",
  },
  footer: {
    marginTop: 24,
    paddingTop: 16,
    borderTop: `1px solid ${COLORS.border}`,
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
  },
  footerText: {
    fontSize: 12,
    color: COLORS.muted,
  },
  footerLinks: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
  },
  footerLink: {
    fontSize: 12,
    color: COLORS.accent,
    fontWeight: 600,
    textDecoration: "none",
  },
  sectionTitle: {
    fontSize: 12,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: COLORS.muted,
    marginBottom: 12,
    fontWeight: 700,
  },
  sectionBlock: {
    marginBottom: 20,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(230px, 1fr))",
    gap: 8,
  },
  card: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 12,
    padding: 14,
    cursor: "pointer",
  },
  cardSoon: {
    opacity: 0.75,
    cursor: "default",
  },
  cardName: {
    fontSize: 15,
    fontWeight: 700,
    marginBottom: 4,
  },
  cardDesc: {
    fontSize: 12,
    color: COLORS.muted,
    lineHeight: 1.5,
  },
  statusBadge: {
    display: "inline-block",
    fontSize: 10,
    fontWeight: 700,
    borderRadius: 999,
    padding: "2px 8px",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  toolFrame: {
    minHeight: "calc(100vh - 52px)",
  },
  loadingFrame: {
    padding: 24,
    color: COLORS.muted,
    fontSize: 14,
  },
  backButton: {
    border: `1px solid ${COLORS.border}`,
    background: COLORS.surface,
    borderRadius: 8,
    padding: "6px 10px",
    color: COLORS.text,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
  },
};
