import { useMemo, useRef, useState } from "react";
import JSZip from "jszip";

const SAMPLE_A = `# This data file generated by 23andMe at: Mon Feb 27 19:26:36 2023
# reference human assembly build 37
# rsid\tchromosome\tposition\tgenotype
rs3094315\t1\t752566\tAA
rs6672840\t1\t752721\tAG
rs4477212\t1\t752832\tGG
rs13302982\t1\t752889\tCC`;

const SAMPLE_B = `#AncestryDNA raw data download
#Data is reported on the + strand using human reference build 37.1
rsid\tchromosome\tposition\tallele1\tallele2
rs3131972\t1\t752721\tA\tG
rs3094315\t1\t752566\tA\tA
rs4477212\t1\t752832\tG\tG
rs99999999\t1\t752889\tC\tT`;

const SAMPLE_MH = `##format=MHv1.0
##chip=GSA
##reference=build37
#
# MyHeritage DNA raw data
# For each SNP -- rsID, chr, pos, genotype result on forward strand, using build37
RSID,CHROMOSOME,POSITION,RESULT
"rs3131972","1","752721","AA"
"rs3094315","1","752566","AA"
"rs4477212","1","752832","GG"
"rs6672840","1","752721","AG"`;

const PAGE_SIZE = 50;
const TEXT_DATA_FILE_REGEX = /\.(txt|csv|tsv)$/i;

const TAB_DEFS = [
  { key: "summary", label: "Summary" },
  { key: "concordant", label: "Concordant" },
  { key: "discordant", label: "Discordant" },
  { key: "rsidMismatch", label: "rsID mismatch" },
  { key: "onlyA", label: "Only in A" },
  { key: "onlyB", label: "Only in B" },
];

const TAB_TONES = {
  summary: { activeBg: "#f3f7ff", activeBorder: "#8fb0e8", activeText: "#1f4f99" },
  concordant: { activeBg: "#ebf8ee", activeBorder: "#8dc99a", activeText: "#2b6a39" },
  discordant: { activeBg: "#ffe9e7", activeBorder: "#de9fba", activeText: "#b42318" },
  rsidMismatch: { activeBg: "#fff6e8", activeBorder: "#e5bb7f", activeText: "#8a5a1f" },
  onlyA: { activeBg: "#eaf2ff", activeBorder: "#8fb0e8", activeText: "#1f4f99" },
  onlyB: { activeBg: "#eaf2ff", activeBorder: "#8fb0e8", activeText: "#1f4f99" },
};

function complement(base) {
  return { A: "T", T: "A", C: "G", G: "C" }[base] || base;
}

// Parse CSV line with support for quoted fields
function parseCSVLine(line) {
  const result = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === "," && !inQuotes) {
      result.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }

  result.push(current.trim());
  return result;
}

function normalizeGeno(value) {
  const clean = String(value || "").replace(/\//g, "").replace(/\s/g, "").toUpperCase();
  if (clean === "00" || clean === "--") return "--";
  return clean.split("").sort().join("");
}

function normalizeChromosome(value) {
  return String(value || "").trim().replace(/^chr/i, "").toUpperCase();
}

function getLocusKey(snp) {
  const chr = normalizeChromosome(snp?.chr);
  const pos = String(snp?.pos || "").trim();
  if (!chr || !pos) return null;
  return `${chr}:${pos}`;
}

function computeChrStats(snpMap) {
  const stats = {};
  const chrSnps = {};
  
  // Group SNPs by chromosome and collect positions
  for (const [, snp] of snpMap) {
    const chr = normalizeChromosome(snp.chr);
    if (!chr) continue;
    
    if (!stats[chr]) {
      stats[chr] = { total: 0, het: 0, hom: 0, noCalls: 0, avgDistance: null };
      chrSnps[chr] = [];
    }
    
    stats[chr].total += 1;
    
    const geno = snp.geno;
    if (geno === "--") {
      stats[chr].noCalls += 1;
    } else if (geno.length === 2 && geno[0] === geno[1]) {
      stats[chr].hom += 1;
    } else if (geno.length === 2 && geno[0] !== geno[1]) {
      stats[chr].het += 1;
    }
    
    chrSnps[chr].push(parseInt(String(snp.pos || "0"), 10));
  }
  
  // Calculate average distance between SNPs for each chromosome
  for (const chr in chrSnps) {
    const positions = chrSnps[chr].sort((a, b) => a - b);
    if (positions.length > 1) {
      let totalGap = 0;
      for (let i = 1; i < positions.length; i++) {
        totalGap += positions[i] - positions[i - 1];
      }
      const avgGap = totalGap / (positions.length - 1);
      stats[chr].avgDistance = avgGap > 1000 ? `${(avgGap / 1000).toFixed(1)} Kb` : `${avgGap.toFixed(0)} bp`;
    }
  }
  
  return stats;
}

function getDbSnpUrl(rsid) {
  return `https://www.ncbi.nlm.nih.gov/snp/${encodeURIComponent(String(rsid || "").trim())}`;
}

function getEnsemblUrl(rsid) {
  return `https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=${encodeURIComponent(String(rsid || "").trim())}`;
}

function detectFormat(lines) {
  const header = lines
    .filter((line) => line.startsWith("#"))
    .join("\n")
    .toLowerCase();

  if (header.includes("23andme")) return "23andMe";
  if (header.includes("ancestrydna") || header.includes("ancestry")) return "AncestryDNA";
  if (header.includes("familytree") || header.includes("ftdna")) return "FamilyTreeDNA";
  if (header.includes("myheritage")) return "MyHeritage";

  const firstData = lines.find((line) => !line.startsWith("#") && line.trim()) || "";
  
  // Detect if CSV (comma-separated) or TSV (tab-separated)
  const isCSV = firstData.includes(",") && !firstData.includes("\t");
  const separator = isCSV ? "," : "\t";
  const columns = firstData.toLowerCase().split(separator);
  
  if (columns.includes("allele1")) return "AncestryDNA";
  if (columns.includes("result")) return isCSV ? "MyHeritage" : "FamilyTreeDNA";
  if (columns.includes("genotype")) return "23andMe";
  return "Unknown";
}

function parseFile(content) {
  const lines = String(content || "").split("\n");
  const format = detectFormat(lines);
  const snps = new Map();
  let columnMap = null;
  let strandNote = "";

  // Detect if file is CSV or TSV based on first data line
  const firstDataLine = lines.find((line) => !line.startsWith("#") && line.trim()) || "";
  const isCSV = firstDataLine.includes(",") && !firstDataLine.includes("\t");
  const lineSplitter = (line) => (isCSV ? parseCSVLine(line) : line.split("\t")).map((col) => col.trim());

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    // Some vendors (e.g., 23andMe) prefix the header row with '#'.
    // Treat that line as the schema row before handling normal comments.
    if (columnMap === null && line.startsWith("#")) {
      const headerLine = line.replace(/^#+\s*/, "");
      const headerColumns = lineSplitter(headerLine).map((col) => col.toLowerCase().replace(/^#/, ""));
      if (headerColumns.includes("rsid") && headerColumns.includes("position")) {
        columnMap = {};
        headerColumns.forEach((name, index) => {
          columnMap[name] = index;
        });
        continue;
      }
    }

    if (line.startsWith("#")) {
      const lower = line.toLowerCase();
      if (lower.includes("+ strand") || lower.includes("+strand")) strandNote = "+ strand";
      else if (lower.includes("forward strand")) strandNote = "forward strand";
      continue;
    }

    const columns = lineSplitter(line);

    if (columnMap === null) {
      const lower = columns.map((col) => col.toLowerCase().replace(/^#/, ""));
      columnMap = {};
      lower.forEach((name, index) => {
        columnMap[name] = index;
      });
      if (!("rsid" in columnMap) && !("position" in columnMap)) columnMap = null;
      continue;
    }

    const rsid = columns[columnMap.rsid] || "";
    const chr = columns[columnMap.chromosome] || columns[columnMap.chr] || "";
    const pos = columns[columnMap.position] || "";
    let rawGeno = "";

    if (columnMap.genotype !== undefined) rawGeno = columns[columnMap.genotype] || "";
    else if (columnMap.result !== undefined) rawGeno = columns[columnMap.result] || "";
    else if (columnMap.allele1 !== undefined) {
      rawGeno = `${columns[columnMap.allele1] || ""}${columns[columnMap.allele2] || ""}`;
    }

    if (normalizeGeno(rawGeno) === "--") rawGeno = "--";

    if (rsid && pos) {
      snps.set(rsid, {
        rsid,
        chr,
        pos,
        rawGeno,
        geno: normalizeGeno(rawGeno),
        hasSlash: rawGeno.includes("/"),
      });
    }
  }

  const usesSlash = Array.from(snps.values()).some((snp) => snp.hasSlash);
  return { format, snps, usesSlash, strandNote, count: snps.size };
}

function compareFiles(fileA, fileB) {
  const discordant = [];
  const rsidMismatch = [];
  const onlyA = [];
  const onlyB = [];
  const concordant = [];
  const processedA = new Set();
  const processedB = new Set();

  const locusB = new Map();
  for (const [rid, snp] of fileB.snps) {
    const locusKey = getLocusKey(snp);
    if (!locusKey) continue;
    locusB.set(locusKey, { rid, snp });
  }

  for (const [rid, snpA] of fileA.snps) {
    if (fileB.snps.has(rid)) {
      const snpB = fileB.snps.get(rid);
      processedA.add(rid);
      processedB.add(rid);

      if (snpA.geno === snpB.geno) {
        concordant.push({ rid, pos: snpA.pos, chr: snpA.chr, genoA: snpA.rawGeno, genoB: snpB.rawGeno });
      } else {
        discordant.push({ rid, pos: snpA.pos, chr: snpA.chr, genoA: snpA.rawGeno, genoB: snpB.rawGeno });
      }
    } else {
      const locusKey = getLocusKey(snpA);
      if (!locusKey || !locusB.has(locusKey)) continue;

      const { rid: ridB, snp: snpB } = locusB.get(locusKey);
      if (!processedB.has(ridB)) {
        processedA.add(rid);
        processedB.add(ridB);
        rsidMismatch.push({ ridA: rid, ridB, pos: snpA.pos, chr: snpA.chr, genoA: snpA.rawGeno, genoB: snpB.rawGeno });
      }
    }
  }

  for (const [rid, snp] of fileA.snps) {
    if (!processedA.has(rid)) onlyA.push(snp);
  }

  for (const [rid, snp] of fileB.snps) {
    if (!processedB.has(rid)) onlyB.push(snp);
  }

  return { discordant, rsidMismatch, onlyA, onlyB, concordant };
}

function makeDiscordantNote(genoA, genoB) {
  const a = normalizeGeno(genoA);
  const b = normalizeGeno(genoB);

  if (a[0] && b[0] && a[0] !== b[0] && a[0] === complement(b[0])) return "possible strand flip";
  if (a.length !== b.length) return "different call length";
  if (a === "--" || b === "--") return "no-call in one";

  const isHet = (value) => value.length === 2 && value[0] !== value[1];
  if (isHet(a) && !isHet(b)) return "het vs hom";
  if (!isHet(a) && isHet(b)) return "hom vs het";
  return "allele mismatch";
}

function getRows(compared, tab) {
  if (!compared) return [];
  if (tab === "discordant") return compared.discordant;
  if (tab === "rsidMismatch") return compared.rsidMismatch;
  if (tab === "onlyA") return compared.onlyA;
  if (tab === "onlyB") return compared.onlyB;
  return compared.concordant;
}

async function readRawFileContent(file) {
  const lowerName = String(file?.name || "").toLowerCase();
  if (!lowerName.endsWith(".zip")) {
    return {
      content: await file.text(),
      displayedName: file.name,
    };
  }

  const zip = await JSZip.loadAsync(await file.arrayBuffer());
  const entries = Object.values(zip.files).filter((entry) => !entry.dir && !entry.name.startsWith("__MACOSX/"));

  if (!entries.length) {
    throw new Error("ZIP archive is empty.");
  }

  const preferredEntry = entries.find((entry) => TEXT_DATA_FILE_REGEX.test(entry.name)) || entries[0];
  return {
    content: await preferredEntry.async("string"),
    displayedName: `${file.name} -> ${preferredEntry.name}`,
  };
}

const styles = {
  wrap: { padding: "14px 14px 20px" },
  heading: { fontSize: 18, fontWeight: 500, marginBottom: 6, paddingInline: 2 },
  subtitle: { fontSize: 13, color: "#5f6f84", marginBottom: 18, paddingInline: 2 },
  dropRow: { display: "flex", gap: 16, marginBottom: 16, flexWrap: "wrap", paddingInline: 2 },
  dropZone: (over, loaded) => ({
    flex: 1,
    minWidth: 280,
    minHeight: 140,
    border: `1.5px ${loaded ? "solid" : "dashed"} ${over || loaded ? "#8fb0e8" : "#c7d3e3"}`,
    borderRadius: 10,
    padding: "16px 14px",
    textAlign: "center",
    cursor: "pointer",
    background: over ? "#f3f7ff" : "#fff",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  }),
  badge: (bg, fg) => ({ borderRadius: 4, padding: "2px 8px", fontSize: 11, fontWeight: 600, background: bg, color: fg }),
  note: { background: "#eaf2ff", borderRadius: 8, padding: "10px 12px", color: "#1f4f99", fontSize: 12, marginBottom: 12 },
  statsRow: { display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 10, marginBottom: 14 },
  stat: (active, tone) => ({
    background: active ? tone.activeBg : "#f5f8fc",
    border: `${active ? 2 : 1}px solid ${active ? tone.activeBorder : "#c7d3e3"}`,
    borderRadius: 8,
    padding: active ? "9px 11px" : "10px 12px",
    textAlign: "center",
    cursor: "pointer",
    transition: "all .15s",
  }),
  statNum: { fontSize: 22, fontWeight: 600 },
  statLbl: { fontSize: 11, color: "#5f6f84", marginTop: 2 },
  tableWrap: { border: "1px solid #c7d3e3", borderRadius: 10, overflow: "auto" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13, fontFamily: "'DM Mono', 'Courier New', monospace" },
  th: { textAlign: "left", fontSize: 11, textTransform: "uppercase", letterSpacing: "0.05em", color: "#5f6f84", background: "#edf3fb", borderBottom: "1px solid #c7d3e3", padding: "8px 10px", whiteSpace: "nowrap" },
  td: { borderBottom: "1px solid #d9e2ef", padding: "7px 10px", whiteSpace: "nowrap" },
  pager: { display: "flex", alignItems: "center", gap: 8, marginTop: 10, fontSize: 12, color: "#5f6f84" },
  pagerBtn: (disabled) => ({
    borderRadius: 8,
    border: "1px solid #c7d3e3",
    background: disabled ? "#f5f8fc" : "#fff",
    color: disabled ? "#9aa8bb" : "#1f4f99",
    fontSize: 12,
    padding: "4px 10px",
    cursor: disabled ? "not-allowed" : "pointer",
  }),
  rsidCellWrap: { display: "inline-flex", flexDirection: "column", gap: 4, whiteSpace: "normal" },
  rsidId: { fontFamily: "'DM Mono', 'Courier New', monospace", fontSize: 12 },
  rsidLinkRow: { display: "inline-flex", gap: 4, flexWrap: "wrap" },
  rsidLinkBadge: {
    display: "inline-block",
    borderRadius: 999,
    border: "1px solid #c7d3e3",
    background: "#f3f7ff",
    color: "#1f4f99",
    padding: "1px 7px",
    fontSize: 10,
    fontWeight: 700,
    textDecoration: "none",
    lineHeight: 1.4,
  },
};

function RsidBadges({ rsid }) {
  const id = String(rsid || "").trim();
  if (!id) return <span>-</span>;

  return (
    <span style={styles.rsidCellWrap}>
      <span style={styles.rsidId}>{id}</span>
      <span style={styles.rsidLinkRow}>
        <a href={getDbSnpUrl(id)} target="_blank" rel="noreferrer" style={styles.rsidLinkBadge}>dbSNP</a>
        <a href={getEnsemblUrl(id)} target="_blank" rel="noreferrer" style={styles.rsidLinkBadge}>Ensembl</a>
      </span>
    </span>
  );
}

function FileDrop({ label, tone, fileData, onFile, onClear }) {
  const inputRef = useRef(null);
  const [dragOver, setDragOver] = useState(false);

  return (
    <div
      style={styles.dropZone(dragOver, Boolean(fileData))}
      onDragOver={(event) => {
        event.preventDefault();
        setDragOver(true);
      }}
      onDragLeave={() => setDragOver(false)}
      onDrop={(event) => {
        event.preventDefault();
        setDragOver(false);
        onFile(event.dataTransfer.files?.[0]);
      }}
      onClick={() => inputRef.current?.click()}
    >
      <span style={styles.badge(tone.bg, tone.fg)}>{label}</span>
      {fileData ? (
        <>
          <span style={styles.badge("#f5f8fc", "#5f6f84")}>{fileData.format}</span>
          <div style={{ fontSize: 12, color: "#5f6f84", wordBreak: "break-all" }}>{fileData.name}</div>
          <div style={{ fontSize: 13, fontWeight: 600 }}>{fileData.count.toLocaleString()} SNPs</div>
          <div style={{ fontSize: 11, color: "#5f6f84" }}>{fileData.usesSlash ? "Format: A/G" : "Format: AG"}</div>
          {fileData.strandNote ? <div style={{ fontSize: 11, color: "#5f6f84" }}>Reported: {fileData.strandNote}</div> : null}
          <button
            type="button"
            onClick={(event) => {
              event.stopPropagation();
              onClear();
            }}
            style={{
              marginTop: 4,
              fontSize: 11,
              padding: "2px 8px",
              cursor: "pointer",
              borderRadius: 6,
              border: "1px solid #c7d3e3",
              background: "transparent",
              color: "#5f6f84",
            }}
          >
            clear
          </button>
        </>
      ) : (
        <>
          <div style={{ fontSize: 24, color: "#9aa8bb", lineHeight: 1 }}>⬆</div>
          <div style={{ fontSize: 13, color: "#5f6f84" }}>Drop file or click to browse</div>
          <div style={{ fontSize: 11, color: "#8a9ab0" }}>.txt tab-delimited</div>
        </>
      )}

      <input
        ref={inputRef}
        type="file"
        accept=".txt,.csv,.tsv,.zip"
        style={{ display: "none" }}
        onChange={(event) => onFile(event.target.files?.[0])}
      />
    </div>
  );
}

export default function DnaFileComparatorApp() {
  const [fileA, setFileA] = useState(null);
  const [fileB, setFileB] = useState(null);
  const [activeTab, setActiveTab] = useState("summary");
  const [errorMessage, setErrorMessage] = useState("");
  const [pageByTab, setPageByTab] = useState({
    summary: 0,
    discordant: 0,
    rsidMismatch: 0,
    onlyA: 0,
    onlyB: 0,
    concordant: 0,
  });

  const compared = useMemo(() => {
    if (!fileA || !fileB) return null;
    return compareFiles(fileA, fileB);
  }, [fileA, fileB]);

  const summaryRows = useMemo(() => {
    if (!fileA || !fileB) return [];
    const statsA = computeChrStats(fileA.snps);
    const statsB = computeChrStats(fileB.snps);
    const allChrs = new Set([...Object.keys(statsA), ...Object.keys(statsB)]);
    const chrOrder = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "X", "Y", "MT"];
    const sorted = Array.from(allChrs).sort((a, b) => {
      const indexA = chrOrder.indexOf(a);
      const indexB = chrOrder.indexOf(b);
      return (indexA === -1 ? 999 : indexA) - (indexB === -1 ? 999 : indexB);
    });
    return sorted.map((chr) => ({ chr, statsA: statsA[chr], statsB: statsB[chr] }));
  }, [fileA, fileB]);

  const activeRows = useMemo(() => {
    if (activeTab === "summary") return summaryRows;
    return getRows(compared, activeTab);
  }, [compared, activeTab, summaryRows]);

  const totalPages = Math.max(1, Math.ceil(activeRows.length / PAGE_SIZE));
  const page = Math.min(pageByTab[activeTab] || 0, totalPages - 1);
  const pagedRows = activeRows.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

  const counts = compared
    ? {
        summary: summaryRows.length,
        discordant: compared.discordant.length,
        rsidMismatch: compared.rsidMismatch.length,
        onlyA: compared.onlyA.length,
        onlyB: compared.onlyB.length,
        concordant: compared.concordant.length,
      }
    : { summary: 0, discordant: 0, rsidMismatch: 0, onlyA: 0, onlyB: 0, concordant: 0 };

  const formatNotes = useMemo(() => {
    if (!fileA || !fileB) return [];
    const notes = [];
    if (fileA.usesSlash !== fileB.usesSlash) {
      notes.push("Genotype notation differs: one uses A/G and the other AG. Values are normalized for comparison.");
    }
    if (fileA.format !== fileB.format) {
      notes.push(`Company formats: ${fileA.format} vs ${fileB.format}`);
    }
    return notes;
  }, [fileA, fileB]);

  const strandNote = useMemo(() => {
    if (!fileA || !fileB) return null;
    if (fileA.strandNote && fileB.strandNote) {
      return `Both files report on the ${fileA.strandNote}. Genotypes are compared directly after normalizing allele order.`;
    }
    return "Strand orientation not detected in both headers. Most companies use + strand; compare files from the same build.";
  }, [fileA, fileB]);

  const readIntoSlot = (slot, file) => {
    if (!file) return;
    setErrorMessage("");

    (async () => {
      try {
        const { content, displayedName } = await readRawFileContent(file);
        const parsed = parseFile(content);
        parsed.name = displayedName;
        if (slot === "A") setFileA(parsed);
        else setFileB(parsed);
      } catch (error) {
        setErrorMessage(`Could not read ${file.name}: ${error?.message || "invalid file"}`);
      }
    })();
  };

  const loadSample = () => {
    const sampleA = parseFile(SAMPLE_A);
    sampleA.name = "sample_23andme.txt";
    const sampleB = parseFile(SAMPLE_B);
    sampleB.name = "sample_ancestry.txt";
    setFileA(sampleA);
    setFileB(sampleB);
    setActiveTab("summary");
    setPageByTab({ summary: 0, discordant: 0, rsidMismatch: 0, onlyA: 0, onlyB: 0, concordant: 0 });
  };

  const setPage = (tab, nextPage) => {
    setPageByTab((prev) => ({ ...prev, [tab]: nextPage }));
  };

  const columns =
    activeTab === "summary"
      ? ["Chr", "File A - Total", "Het", "Hom", "No-Calls", "Avg Dist", "File B - Total", "Het", "Hom", "No-Calls", "Avg Dist"]
      : activeTab === "discordant"
        ? ["rsID", "Chr", "Pos", "Genotype (A)", "Genotype (B)", "Notes"]
        : activeTab === "rsidMismatch"
          ? ["rsID (A)", "rsID (B)", "Chr", "Pos", "Geno (A)", "Geno (B)"]
          : ["rsID", "Chr", "Pos", "Genotype"];

  return (
    <div style={styles.wrap}>
      <h2 style={styles.heading}>DNA raw file comparator</h2>
      <p style={styles.subtitle}>Compare SNP files from 23andMe, AncestryDNA, FamilyTreeDNA, and MyHeritage.</p>

      <div style={styles.dropRow}>
        <FileDrop
          label="File A"
          tone={{ bg: "#eaf2ff", fg: "#1f4f99" }}
          fileData={fileA}
          onFile={(file) => readIntoSlot("A", file)}
          onClear={() => setFileA(null)}
        />
        <FileDrop
          label="File B"
          tone={{ bg: "#fff6e8", fg: "#8a5a1f" }}
          fileData={fileB}
          onFile={(file) => readIntoSlot("B", file)}
          onClear={() => setFileB(null)}
        />
      </div>

      {errorMessage ? <div style={{ ...styles.note, background: "#ffe9e7", color: "#b42318" }}>{errorMessage}</div> : null}

      {!fileA && !fileB ? (
        <button
          type="button"
          onClick={loadSample}
          style={{
            display: "block",
            margin: "-6px auto 16px",
            fontSize: 12,
            padding: "4px 12px",
            cursor: "pointer",
            borderRadius: 8,
            border: "1px solid #c7d3e3",
            background: "transparent",
            color: "#5f6f84",
          }}
        >
          Load sample data
        </button>
      ) : null}

      <div style={styles.statsRow}>
        {TAB_DEFS.map((tab) => {
          const tone = TAB_TONES[tab.key];
          const isActive = activeTab === tab.key;
          return (
            <button
              key={`pill-${tab.key}`}
              type="button"
              style={styles.stat(isActive, tone)}
              onClick={() => {
                setActiveTab(tab.key);
                setPage(tab.key, 0);
              }}
            >
              <div style={{ ...styles.statNum, color: isActive ? tone.activeText : "#17212f" }}>
                {counts[tab.key].toLocaleString()}
              </div>
              <div style={styles.statLbl}>{tab.label}</div>
            </button>
          );
        })}
      </div>

      {formatNotes.map((note, index) => (
        <div key={`note-${index}`} style={styles.note}>{note}</div>
      ))}

      {compared ? (
        <>
          <div style={styles.note}>{strandNote}</div>

          <div style={styles.tableWrap}>
            <table style={styles.table}>
              <thead>
                <tr>
                  {columns.map((column, colIndex) => {
                    const isSummarySeparator = activeTab === "summary" && (colIndex === 0 || colIndex === 5);
                    return (
                      <th key={column} style={{ ...styles.th, ...(isSummarySeparator ? { borderRight: "2px solid #8fb0e8" } : {}) }}>{column}</th>
                    );
                  })}
                </tr>
              </thead>
              <tbody>
                {!pagedRows.length ? (
                  <tr>
                    <td style={styles.td} colSpan={columns.length}>No entries</td>
                  </tr>
                ) : null}

                {pagedRows.map((row, index) => {
                  const key = `${activeTab}-${index}-${row.rid || row.rsid || row.ridA || row.chr || "row"}`;
                  
                  if (activeTab === "summary") {
                    const statA = row.statsA || { total: 0, het: 0, hom: 0, noCalls: 0, avgDistance: null };
                    const statB = row.statsB || { total: 0, het: 0, hom: 0, noCalls: 0, avgDistance: null };
                    return (
                      <tr key={key}>
                        <td style={{ ...styles.td, borderRight: "2px solid #8fb0e8" }}><strong>{row.chr}</strong></td>
                        <td style={styles.td}>{statA.total.toLocaleString()}</td>
                        <td style={styles.td}>{statA.het.toLocaleString()}</td>
                        <td style={styles.td}>{statA.hom.toLocaleString()}</td>
                        <td style={styles.td}>{statA.noCalls.toLocaleString()}</td>
                        <td style={{ ...styles.td, borderRight: "2px solid #8fb0e8", fontSize: 12, color: "#5f6f84", fontWeight: 500 }}>{statA.avgDistance || "—"}</td>
                        <td style={styles.td}>{statB.total.toLocaleString()}</td>
                        <td style={styles.td}>{statB.het.toLocaleString()}</td>
                        <td style={styles.td}>{statB.hom.toLocaleString()}</td>
                        <td style={styles.td}>{statB.noCalls.toLocaleString()}</td>
                        <td style={{ ...styles.td, fontSize: 12, color: "#5f6f84", fontWeight: 500 }}>{statB.avgDistance || "—"}</td>
                      </tr>
                    );
                  }

                  if (activeTab === "discordant") {
                    return (
                      <tr key={key}>
                        <td style={styles.td}><RsidBadges rsid={row.rid} /></td>
                        <td style={styles.td}>{row.chr}</td>
                        <td style={styles.td}>{row.pos}</td>
                        <td style={{ ...styles.td, color: "#b42318" }}>{row.genoA}</td>
                        <td style={{ ...styles.td, color: "#b42318" }}>{row.genoB}</td>
                        <td style={{ ...styles.td, fontFamily: "'DM Sans', 'Segoe UI', sans-serif", fontSize: 11, color: "#5f6f84" }}>{makeDiscordantNote(row.genoA, row.genoB)}</td>
                      </tr>
                    );
                  }

                  if (activeTab === "rsidMismatch") {
                    return (
                      <tr key={key}>
                        <td style={styles.td}><RsidBadges rsid={row.ridA} /></td>
                        <td style={styles.td}><RsidBadges rsid={row.ridB} /></td>
                        <td style={styles.td}>{row.chr}</td>
                        <td style={styles.td}>{row.pos}</td>
                        <td style={styles.td}>{row.genoA}</td>
                        <td style={styles.td}>{row.genoB}</td>
                      </tr>
                    );
                  }

                  if (activeTab === "onlyA" || activeTab === "onlyB") {
                    return (
                      <tr key={key}>
                        <td style={styles.td}><RsidBadges rsid={row.rsid} /></td>
                        <td style={styles.td}>{row.chr}</td>
                        <td style={styles.td}>{row.pos}</td>
                        <td style={styles.td}>{row.rawGeno}</td>
                      </tr>
                    );
                  }

                  return (
                    <tr key={key}>
                      <td style={styles.td}><RsidBadges rsid={row.rid} /></td>
                      <td style={styles.td}>{row.chr}</td>
                      <td style={styles.td}>{row.pos}</td>
                      <td style={styles.td}>{row.genoA}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {totalPages > 1 ? (
            <div style={styles.pager}>
              <button
                type="button"
                disabled={page === 0}
                style={styles.pagerBtn(page === 0)}
                onClick={() => setPage(activeTab, Math.max(0, page - 1))}
              >
                prev
              </button>
              <span>Page {page + 1} of {totalPages} ({activeRows.length.toLocaleString()} entries)</span>
              <button
                type="button"
                disabled={page >= totalPages - 1}
                style={styles.pagerBtn(page >= totalPages - 1)}
                onClick={() => setPage(activeTab, Math.min(totalPages - 1, page + 1))}
              >
                next
              </button>
            </div>
          ) : null}
        </>
      ) : null}
    </div>
  );
}
