import { COLORS, MONO_FONT, UI_FONT } from "../styles/light-theme";

const S = {
  outer: {
    display:    "flex",
    height:     "100%",
    fontFamily: UI_FONT,
    background: COLORS.bg,
    overflow:   "hidden",
  },
  thumbStrip: {
    width:         110,
    minWidth:      110,
    minHeight:     0,
    overflowY:     "auto",
    borderRight:   `1px solid ${COLORS.border}`,
    background:    "#eef0f5",
    padding:       "8px 0",
    display:       "flex",
    flexDirection: "column",
    gap:           4,
  },
  thumb: {
    margin:      "0 6px",
    padding:     "5px 5px 3px",
    borderRadius: 5,
    cursor:      "pointer",
    border:      "2px solid transparent",
    transition:  "border-color 0.12s, background 0.12s",
    overflow:    "hidden",
    flexShrink:  0,
  },
  thumbActive: {
    border:     `2px solid ${COLORS.accent}`,
    background: COLORS.accentSoft,
  },
  thumbNum: {
    textAlign:  "center",
    fontSize:   9,
    color:      COLORS.muted,
    marginTop:  3,
    fontFamily: MONO_FONT,
  },
  left: {
    width:         280,
    minWidth:      280,
    padding:       "1.25rem 1rem",
    borderRight:   `1px solid ${COLORS.border}`,
    background:    COLORS.surface,
    overflowY:     "auto",
    display:       "flex",
    flexDirection: "column",
    gap:           "1rem",
  },
  right: {
    flex:          1,
    display:       "flex",
    flexDirection: "column",
    overflow:      "hidden",
    background:    COLORS.bg,
  },
  h1: {
    fontFamily:    "Georgia, serif",
    fontSize:      19,
    fontWeight:    400,
    color:         COLORS.text,
    margin:        0,
    letterSpacing: "-0.02em",
  },
  sub: {
    fontSize:      9,
    color:         COLORS.muted,
    letterSpacing: "0.07em",
    margin:        0,
  },
  error: {
    padding:      "8px 12px",
    background:   "#fff5f5",
    border:       `1px solid ${COLORS.error}`,
    borderRadius: 6,
    fontSize:     12,
    color:        COLORS.error,
  },
  rotRow: {
    display:    "flex",
    alignItems: "center",
    gap:        5,
    flexWrap:   "wrap",
  },
  rotVal: {
    fontFamily: MONO_FONT,
    fontSize:   13,
    fontWeight: 600,
    color:      COLORS.text,
    minWidth:   36,
    textAlign:  "center",
  },
  rotBtn: {
    padding:      "3px 8px",
    border:       `1px solid ${COLORS.border}`,
    borderRadius: 5,
    background:   COLORS.surface,
    color:        COLORS.text,
    cursor:       "pointer",
    fontFamily:   MONO_FONT,
    fontSize:     11,
  },
  resetBtn: {
    alignSelf:    "flex-start",
    padding:      "3px 10px",
    fontSize:     11,
    fontFamily:   MONO_FONT,
    border:       `1px solid ${COLORS.border}`,
    borderRadius: 5,
    background:   COLORS.surface,
    color:        COLORS.muted,
    cursor:       "pointer",
  },
  hint: {
    fontSize:   10,
    color:      COLORS.muted,
    margin:     0,
    lineHeight: 1.5,
  },
  placeholder: {
    flex:           1,
    display:        "flex",
    flexDirection:  "column",
    alignItems:     "center",
    justifyContent: "center",
    gap:            12,
  },
  track: {
    width:        200,
    height:       3,
    background:   COLORS.border,
    borderRadius: 2,
  },
  bar: {
    height:       "100%",
    background:   COLORS.accent,
    borderRadius: 2,
    transition:   "width 0.2s",
  },
  navBar: {
    display:      "flex",
    alignItems:   "center",
    gap:          10,
    padding:      "8px 16px",
    borderBottom: `1px solid ${COLORS.border}`,
    background:   COLORS.surface,
    flexShrink:   0,
  },
  navBtn: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    width:          28,
    height:         28,
    border:         `1px solid ${COLORS.border}`,
    borderRadius:   6,
    background:     COLORS.surface,
    color:          COLORS.text,
  },
  navLabel: {
    fontSize:  12,
    color:     COLORS.muted,
    flex:      1,
    textAlign: "center",
  },
  rotBadge: {
    fontSize:     10,
    padding:      "2px 7px",
    background:   COLORS.accentSoft,
    color:        COLORS.accent,
    borderRadius: 4,
    fontFamily:   MONO_FONT,
  },
  viewer: {
    flex:           1,
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    padding:        24,
    overflow:       "hidden",
  },
  actionRow: {
    display: "flex",
    gap:     6,
  },
  deskewBtn: {
    flex:         1,
    padding:      "4px 8px",
    fontSize:     11,
    fontFamily:   MONO_FONT,
    border:       `1px solid ${COLORS.accent}`,
    borderRadius: 5,
    background:   COLORS.accentSoft,
    color:        COLORS.accent,
    cursor:       "pointer",
    textAlign:    "center",
  },
  deskewBtnActive: {
    background: COLORS.accent,
    color:      "#fff",
  },
};

export default S;
