// ── Styles ────────────────────────────────────────────────
const styles = {
  page: {
    background: "#07090f",
    minHeight: "100vh",
    padding: "32px 28px 60px",
    fontFamily: "Syne, sans-serif",
    color: "#c8d4f0",
  },
  h1: {
    fontSize: 30,
    fontWeight: 800,
    letterSpacing: "-0.5px",
    color: "#dce8ff",
    marginBottom: 4,
  },
  sub: { color: "#8a9bb5", fontSize: 14, lineHeight: 1.6, maxWidth: "100vw" },
  badge: {
    background: "#4f8ef720",
    border: "1px solid #4f8ef740",
    color: "#4f8ef7",
    borderRadius: 20,
    padding: "3px 10px",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: ".5px",
    display: "inline-block",
    marginLeft: 12,
  },
  textarea: {
    width: "100%",
    height: 120,
    background: "#0e1422",
    border: "1px solid #1e2d48",
    borderRadius: 8,
    color: "#c8d4f0",
    fontFamily: "JetBrains Mono,monospace",
    fontSize: 12,
    padding: 12,
    resize: "vertical",
    outline: "none",
    minWidth: 0,
  },
  dropzone: {
    border: "2px dashed #1e2d48",
    borderRadius: 8,
    padding: "14px 20px",
    textAlign: "center",
    color: "#4e5f80",
    fontSize: 12,
    cursor: "pointer",
    background: "#0e1422",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    transition: "all .2s",
    marginTop: 8,
  },
  btnPrimary: {
    border: "none",
    borderRadius: 8,
    padding: "4px 20px",
    cursor: "pointer",
    fontFamily: "Syne,sans-serif",
    fontSize: 12,
    fontWeight: 700,
    background: "#4f8ef7",
    color: "#fff",
  },
  btnSecond: {
    border: "1px solid #1e2d48",
    borderRadius: 8,
    padding: "4px 20px",
    cursor: "pointer",
    fontFamily: "Syne,sans-serif",
    fontSize: 12,
    fontWeight: 700,
    background: "#4f8ef7",
    color: "#2e2f80",
  },
  statsBar: {
    display: "flex",
    gap: 20,
    padding: "10px 16px",
    alignItems: "center",
    background: "#0e1422",
    border: "1px solid #1e2d48",
    borderRadius: 8,
    marginBottom: 16,
    flexWrap: "wrap",
    fontSize: 12,
  },
  sep: { width: 1, height: 16, background: "#1e2d48", flexShrink: 0 },
  viewer: {
    display: "flex",
    background: "#0e1422",
    border: "1px solid #1e2d48",
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 16,
  },
  labCol: {
    flexShrink: 0,
    background: "#131a2e",
    borderRight: "1px solid #1e2d48",
  },
  labCell: {
    display: "flex",
    alignItems: "center",
    padding: "0 12px",
    fontFamily: "JetBrains Mono,monospace",
    fontSize: 11,
    fontWeight: 600,
    color: "#4eafe0",
    whiteSpace: "nowrap",
    borderTop: "1px solid #1e2d48",
  },
  featPanel: {
    background: "#0e1422",
    border: "1px solid #1e2d48",
    borderRadius: 10,
    padding: 16,
  },
  featItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 11,
    fontFamily: "JetBrains Mono,monospace",
    padding: "4px 8px",
    borderRadius: 4,
    background: "#131a2e",
    marginBottom: 3,
  },
  navButton: {
    padding: "8px 12px",
    fontSize: 14,
    fontWeight: 600,
    color: "#dce8ff",
    background: "#1e2d48",
    border: "1px solid #4e5f80",
    borderRadius: 4,
    cursor: "pointer",
    transition: "background 0.2s",
  },
};

export default styles;
