const S = {
  root: {
    minHeight: "100vh",
    background: "#f9f9f9", // Light background
    color: "#222", // Darker general text
    fontFamily: "'Courier New',monospace",
    display: "flex",
    flexDirection: "column",
  },
  hdr: {
    padding: "14px 24px",
    borderBottom: "1px solid rgba(0,0,0,0.1)",
    background: "#ffffff", // White header background
    display: "flex",
    alignItems: "baseline",
    gap: 14,
    flexWrap: "wrap",
  },
  logo: { fontSize: 20, fontWeight: 700 },
  lm: { color: "#333" }, // Dark text for logo
  la: { color: "#007acc" }, // Blue accent
  sub: {
    fontSize: 9,
    color: "rgba(34,34,34,0.7)", // Darker subtext
    letterSpacing: "0.13em",
    textTransform: "uppercase",
  },
  body: { display: "flex", flex: 1, overflow: "hidden" },
  aside: {
    width: 285,
    minWidth: 255,
    borderRight: "1px solid rgba(0,0,0,0.1)",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    overflowY: "auto",
  },
  main: {
    flex: 1,
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    overflowY: "auto",
  },
  card: {
    background: "#ffffff", // White card background
    border: "1px solid rgba(0,0,0,0.1)",
    borderRadius: 6,
    padding: "12px 12px",
  },
  cLbl: {
    fontSize: 12,
    letterSpacing: "0.11em",
    color: "#005fa3", // Slightly darker blue accent for labels
    fontWeight: 800,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  drop: {
    border: "2px dashed rgba(0,0,0,0.15)",
    borderRadius: 5,
    padding: "16px 12px",
    textAlign: "center",
    cursor: "pointer",
    transition: "all 0.12s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 68,
  },
  dropOn: { borderColor: "#007acc", background: "rgba(0,122,204,0.04)" },
  dropFull: {
    borderStyle: "solid",
    borderColor: "rgba(0,0,0,0.22)",
    justifyContent: "flex-start",
    textAlign: "left",
  },
  dropHint: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 7,
  },
  dIco: { fontSize: 22, color: "rgba(0,0,0,0.25)" },
  dTxt: {
    fontSize: 11,
    color: "rgba(34,34,34,0.6)", // Darker hint text
    textAlign: "center",
    maxWidth: 260,
    lineHeight: 1.65,
  },
  browse: {
    fontSize: 10,
    color: "#007acc",
    border: "1px solid rgba(2, 75, 124, 0.66)",
    padding: "3px 10px",
    borderRadius: 3,
    cursor: "pointer",
    letterSpacing: "0.1em",
  },
  fileRow: { display: "flex", alignItems: "flex-start", gap: 9, width: "100%" },
  fIco: { fontSize: 18, color: "#007acc", flexShrink: 0, lineHeight: 1.3 },
  fn: { fontSize: 12, wordBreak: "break-all", color: "#1a2c43" },
  fm: { fontSize: 11, color: "rgba(34, 34, 34, 0.77)", marginTop: 2 },
  xBtn: {
    marginLeft: "auto",
    background: "none",
    border: "none",
    color: "rgba(34,34,34,0.4)", // Darker close button text
    cursor: "pointer",
    fontSize: 11,
    flexShrink: 0,
    padding: 0,
  },
  ta: {
    width: "100%",
    background: "rgba(0,0,0,0.05)",
    border: "1px solid rgba(0,0,0,0.1)",
    borderRadius: 4,
    color: "#222", // Darker textarea text
    fontFamily: "'Courier New',monospace",
    fontSize: 13,
    padding: "8px 10px",
    resize: "vertical",
    boxSizing: "border-box",
    outline: "none",
    lineHeight: 1.65,
  },
  tRow: { display: "flex", alignItems: "center", gap: 9, marginBottom: 9 },
  tBtn: {
    width: 30,
    height: 30,
    border: "1px solid #080c0b",
    background: "#00ff9d",
    color: "#080c0b",
    fontSize: 17,
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none",
  },
  tDisplay: { flex: 1, textAlign: "center" },
  tNum: {
    fontSize: 26,
    fontWeight: 700,
    color: "#00ff9d",
    display: "block",
    lineHeight: 1,
  },
  tSub: {
    fontSize: 11,
    color: "rgba(34, 34, 34, 0.84)", // Darker thread subtitle
    letterSpacing: "0.08em",
  },
  coreBar: { display: "flex", gap: 3, flexWrap: "wrap", marginBottom: 8 },
  core: {
    width: 12,
    height: 12,
    borderRadius: 2,
    transition: "background 0.2s",
  },
  tnotes: { display: "flex", flexDirection: "column", gap: 3 },
  tn: {
    fontSize: 11,
    color: "rgba(39, 42, 40, 0.93)",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  tnd: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "rgba(83, 91, 87, 0.93)",
    display: "inline-block",
    flexShrink: 0,
  },
  runBtn: {
    width: "100%",
    padding: "11px 0",
    background: "#00ff9d",
    color: "#080c0b",
    border: "none",
    borderRadius: 5,
    fontFamily: "'Courier New',monospace",
    fontWeight: 700,
    fontSize: 11,
    letterSpacing: "0.16em",
    transition: "opacity 0.15s",
  },
  cancelBtn: {
    width: "100%",
    padding: "11px 0",
    background: "rgba(255,50,50,0.07)",
    color: "#ff5555",
    border: "1px solid rgba(255,50,50,0.22)",
    borderRadius: 5,
    fontFamily: "'Courier New',monospace",
    fontWeight: 700,
    fontSize: 11,
    letterSpacing: "0.16em",
    cursor: "pointer",
  },
  pipe: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  stage: { flex: 1, minWidth: 90 },
  stLbl: {
    fontSize: 12,
    color: "rgba(38, 80, 64, 0.94)",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  barT: {
    height: 5,
    background: "rgba(255, 255, 255, 0.2)",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 4,
  },
  barF: {
    height: "100%",
    borderRadius: 3,
    transition: "width 0.35s ease,background 0.3s",
  },
  stInfo: { fontSize: 11, color: "rgba(83, 89, 86, 0.8)" },
  arrow: {
    color: "rgba(0,255,157,0.22)",
    fontSize: 16,
    alignSelf: "center",
    paddingTop: 8,
    flexShrink: 0,
  },
  qGrid: { display: "flex", gap: 2, flexWrap: "wrap", marginBottom: 4 },
  qCell: {
    width: 8,
    height: 8,
    borderRadius: 2,
    transition: "background 0.12s",
  },
  wGrid: { display: "flex", gap: 4, flexWrap: "wrap" },
  wCard: {
    border: "1px solid",
    borderRadius: 4,
    padding: "5px 7px",
    minWidth: 46,
    transition: "all 0.2s",
  },
  wTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 2,
  },
  wId: {
    fontSize: 10,
    color: "rgb(88, 93, 91)",
    letterSpacing: "0.08em",
  },
  wDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    transition: "background 0.3s",
  },
  wRec: { fontSize: 9, color: "rgba(93, 101, 97, 0.63)" },
  wHit: { fontSize: 9, color: "#56625d" },
  ctrs: {
    display: "flex",
    gap: 20,
    flexWrap: "wrap",
    borderTop: "1px solid rgba(0, 255, 157, 0.57)",
    paddingTop: 9,
    marginTop: 2,
  },
  ctr: { display: "flex", gap: 6, alignItems: "baseline" },
  ctrV: { fontSize: 13, fontWeight: 700, color: "#00ff9d" },
  ctrL: {
    fontSize: 9,
    color: "rgba(34, 34, 34, 0.77)", // Darker counter label
    letterSpacing: "0.08em",
  },
  sumRow: {
    display: "flex",
    background: "rgba(79, 79, 79, 0.42)",
    borderRadius: 4,
    overflow: "hidden",
    border: "2px solid rgba(0, 255, 157, 0.68)",
    marginBottom: 12,
  },
  stat: { flex: 1, padding: "10px 8px", textAlign: "center" },
  sN: { fontSize: 19, fontWeight: 800, color: "#03915b" },
  sL: {
    fontSize: 10,
    color: "rgba(44, 49, 46, 0.9)",
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    marginTop: 2,
  },
  sdiv: { width: 1, background: "rgba(185, 188, 187, 0.5)" },
  mList: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    maxHeight: 380,
    overflowY: "auto",
  },
  mCard: {
    background: "rgba(187, 185, 185, 0.2)",
    border: "1px solid rgba(0,255,157,0.07)",
    borderRadius: 4,
    padding: "7px 9px",
  },
  mHdr: {
    fontSize: 14,
    color: "rgba(34, 34, 34, 0.65)", // Darker match header
    marginBottom: 4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  mSeq: { fontSize: 14, wordBreak: "break-all", lineHeight: 1.55 },
  seqT: { color: "rgba(49, 58, 52, 0.87)" },
  seqH: {
    background: "rgba(43, 58, 58, 0.23)",
    color: "#04994c",
    borderRadius: 2,
    padding: "0 1px",
  },
  mTag: { fontSize: 14, color: "rgba(34, 34, 34, 0.79)", marginTop: 3 },
  noMatch: {
    fontSize: 12,
    color: "rgba(34,34,34,0.4)", // Darker no match text
    textAlign: "center",
    padding: "14px 0",
  },
  trunc: {
    fontSize: 14,
    color: "rgba(34,34,34,0.4)", // Darker truncation text
    textAlign: "center",
    padding: "5px 0",
  },
  empty: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 11,
    minHeight: 180,
    border: "1px dashed rgba(0,255,157,0.06)",
    borderRadius: 6,
  },
  eIco: { fontSize: 30, color: "rgba(0,255,157,0.1)" },
  eTxt: {
    fontSize: 11,
    color: "rgba(34, 34, 34, 0.68)", // Darker empty state text
    textAlign: "center",
    maxWidth: 260,
    lineHeight: 1.65,
  },
};

export default S;
